{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: clouddns
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: none";
spec:
  rules:
  - host: "api-{{ include "hostname" .Values.service.url }}"
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ $serviceName }}
            servicePort: http-backend
  - host: "{{ include "hostname" .Values.service.url }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName }}
          servicePort: http-frontend
  tls:
  - secretName: {{ .Values.service.domain }}-tls
    hosts:
    - "*.{{ .Values.service.domain }}"
{{- end }}
