aws:
  receive_message:
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp
  region: eu-central-1

concurrency: 5
pidfile: tmp/pids/shoryuken.pid
queues:
  - https://sqs.eu-central-1.amazonaws.com/003688427525/mailers