aws:
  access_key_id: <%= Rails.application.credentials.staging_aws_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.staging_aws_secret_access_key %>
  region: eu-central-1
  bucket: assets.itsmycargo.com

fixer:
  api_key: <%= Rails.application.credentials.staging_fixer_api_key %>

google:
  api_key: <%= Rails.application.credentials.staging_google_api_key %>

smtp:
  host: sendgrid.net
  domain: itsmycargo.com
  username: itsmycargo
  password: <%= Rails.application.credentials.staging_smtp_password %>
